### PR TITLE
add support for epic_id, external_id, and labels

### PR DESCRIPTION
**Pull request by greghaygood**
Hey! I added a few extra fields that I needed for an import.

### CODE REVIEW

**Comment by mikkelson** [comment]
Cheers, Greg.

**Comment by fourmi4x** [comment]
Hi, thank you very much for this script.

I tried to use the "epic_id" field with your hosted version here : http://jamesmikkelson.com/clubhouse
but I can't get it to work
=> has this latest commit be deployed on your hosted version ?

Thanks a lot,
Xavier

**Comment by mikkelson** [comment]
Hi Xavier,

You are correct, the last two contributions were not deployed on the hosted version. I've updated this now, you should be good.

Please let me know how you get on

**Comment by fourmi4x** [comment]
Hi,
Thanks for your feedback.
I can't manage to get it work, here is the example file I use, I just add epic_id at the end of the header row, and some existing epic_id at the end of the lines :

project_id,name,story_type,description,epic_id
14,newtest3,bug,The link to the home page from the top menu does not work,7
6,newtest4,feature,Users should be able to reset their passwords using email,24

Can't manage to get labels working either.
Is there something I'm missing ?

**Pull request merged**
